# .readthedocs.yaml
# configuration file for publishing Python API documentation on "Read the Docs"
#
# configuration file reference: https://docs.readthedocs.io/en/stable/config-file/v2.html
# job configuration: https://app.readthedocs.org/projects/selenium-python-api-docs
# published docs: https://selenium-python-api-docs.readthedocs.io

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - pip install -r py/docs/requirements.txt
    - pip install -r py/requirements.txt
    - cd py && python3 generate_api_module_listing.py && cd
    - PYTHONPATH=py sphinx-autogen -o $READTHEDOCS_OUTPUT/html py/docs/source/api.rst
    - PYTHONPATH=py sphinx-build -b html -d build/docs/doctrees py/docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: py/docs/source/conf.py
